---
- name: File Content
  hosts: all
  become: yes
  tasks:
    - name: Copy new MOTD content
      copy:
        dest: /etc/motd
        content: "{{ item.motd + '\n' }}"
        force: yes
      when: inventory_hostname in groups[item.inv_group]
      loop:
        - { inv_group: "proxy", motd: "Welcome to HAProxy server" }
        - { inv_group: "webservers", motd: "Welcome to Apache server" }
        - { inv_group: "database", motd: "Welcome to MySQL server" }