---
- name: Security
  hosts: webservers
  become: yes
  vars:
    selinux_booleans:
      - { name: 'httpd_can_network_connect', state: 'on', persistent: 'yes' }
  roles:
    - role: { role: rhel-system-roles.selinux }