---
- name: Create and Use Templates to Create Customised Configuration Files
  hosts: all
  become: yes
  tasks:
    - name: Create server list
      template:
        src: server_list.j2
        dest: /etc/server_list.txt
        owner: ansible
        mode: '0600'
        setype: net_conf_t
      when: inventory_hostname in groups['database']
