---
- hosts: all
  become: yes
  vars:
  vars_files:
  roles:
  tasks:
    - name: Create LVM device
      block:
        - name: Create LVM on /dev/vdb
          parted:
            device: /dev/vdb
            flags: [ lvm ]
            state: present
            number: 1
          register: _dev_stat
      rescue:
        - name: Debug
          debug:
            msg: "Device /dev/vdb on {{ hostvars[inventory_hostname]['ansible_facts']['fqdn'] }} does not exists."
    - name: Create VG group
      block:
        - name: Create VG on /dev/vdb1
          lvg:
            pvs: /dev/vdb1
            vg: vg_data
          register: _vg_stat
      rescue:
        - name: Debug
          debug:
            msg: "Primary partition number 1 {{ hostvars[inventory_hostname]['ansible_facts']['fqdn'] }} already exist."
      when: _dev_stat is succeeded
    - block:
        - name: Create LVM
          lvol:
            vg: vg_data
            lv: lv_data
            size: 800m
          register: _lv_stat
      rescue:
        - name: Debug
          debug:
            msg: "VG group vg_data doesn't have enough storage on {{ hostvars[inventory_hostname]['ansible_facts']['fqdn'] }}."
      when: _dev_stat is succeeded and _vg_stat is succeeded
    - block:
        - name: Format filesystem
          filesystem:
            device: /dev/vg_data/lv_data
            fstype: ext4
        - name: Create /data dir
          file:
            state: directory
            path: /data
            mode: '0755'
        - name: Mount lvm to /data
          mount:
            src: /dev/vg_data/lv_data
            path: /data
            fstype: ext4
            state: mounted
      when: _dev_stat is succeeded and _vg_stat is succeeded and _lv_stat is succeeded