---
- name: Use Conditionals to Control Play Execution
  hosts: all
  become: yes
  tasks:
    - name: Set vm.swapiness
      sysctl:
        name: vm.swappiness
        value: 10
        state: present
      when: ansible_facts['memtotal_mb'] > 2048
    - name: Message if not enough memory
      debug:
        msg: "Server memory less than 2048MB"
      when: ansible_facts['memtotal_mb'] < 2048